# fly.toml generated for OpenFrontIO / Frontline
app = "frontline"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"
  NODE_ENV = "production"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  # HTTP public on 80 → redirect to 443 TLS
  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
